
name: PR Check

on:
  pull_request:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simple mock step
        run: |
          echo "🔍 Выполняем простую проверку..."
          # здесь могла бы быть твоя сборка или тесты
          echo "✅ Проверка пройдена успешно"
